version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "yarn"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "yarn"
    directory: "/statusboard"
    schedule:
      interval: "weekly"
