name: Lighthouse CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: statusboard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn --frozen-lockfile && yarn global add @lhci/cli@0.8.x
      - run: yarn run build
      - run: lhci autorun
