name: Tests
on:
    - push:
        paths:
            - 'statusboard/**'
    - workflow_dispatch

jobs:
    defaults:
      run:
        working-directory: statusboard
    test:
        runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16'
      - run: yarn --frozen-lockfile
      - run: yarn run test
